FROM elixir:1.5.1
ENV DEBIAN_FRONTEND=noninteractive

EXPOSE 8000
ENV PORT=8000 MIX_ENV=prod REPLACE_OS_VARS=true SHELL=/bin/bash

WORKDIR /app
COPY ./open_budget.tar.gz ./
RUN tar xfz open_budget.tar.gz

ENTRYPOINT ["bin/open_budget"]